import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import assignmentsRouter from "./assignments";
import warehouseRouter from "./warehouse";
import trainingRouter from "./training";
import novaHelpRouter from "./novaHelp";
import novaDemoBrainRouter from "./novaDemoBrain";
import transcribeRouter from "./transcribe";
import requestAccessRouter from "./requestAccess";
import createCheckoutRouter from "./createCheckout";
import novaDemoAgentRouter from "./novaDemoAgent";
import invitesRouter from "./invites";
import authCodesRouter from "./authCodes";
import leadsRouter from "./leads";
import metricsRouter from "./metrics";
import socialRouter from "./social";
import novaSalesChatRouter from "./novaSalesChat";
import novaChatLogsRouter from "./novaChatLogs";
import novaWelcomeChatRouter from "./novaWelcomeChat";
import contractsRouter from "./contracts";
import mistakesRouter from "./mistakes.js";
import trialRouter from "./trial.js";
import slotMasterRouter from "./slotMaster.js";
import alertsRouter from "./alerts.js";
import positionsRouter from "./positions.js";
import pickingReportsRouter from "./pickingReports.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(trialRouter);
router.use(assignmentsRouter);
router.use(warehouseRouter);
router.use(trainingRouter);
router.use(novaHelpRouter);
router.use(novaDemoBrainRouter);
router.use(novaDemoAgentRouter);
router.use(transcribeRouter);
router.use(requestAccessRouter);
router.use(createCheckoutRouter);
router.use(invitesRouter);
router.use(authCodesRouter);
router.use(leadsRouter);
router.use(metricsRouter);
router.use(socialRouter);
router.use(novaSalesChatRouter);
router.use(novaChatLogsRouter);
router.use(novaWelcomeChatRouter);
router.use(contractsRouter);
router.use(mistakesRouter);
router.use(slotMasterRouter);
router.use(alertsRouter);
router.use(positionsRouter);
router.use(pickingReportsRouter);

export default router;
